name: Check and Deploy
on:
  push:
    branches: ['*']
    tags: ["*"]

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Run unit tests
        run: sbt toplBtcBridge/test
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: topl-btc-bridge/target/test-reports/
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-20.04
    needs: unit-test
    services:
      # Label used to access the service container
      bifrost:
        # Docker Hub image
        image: docker.io/toplprotocol/bifrost-node:2.0.0-alpha10
        #
        ports:
          - 9084:9084 
      bitcoin:
        # Docker Hub image
        image: docker.io/1maa/bitcoin:v25-regtest
        #
        ports:
          - 18444:18444  
        options: --name bitcoin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Generate new address
        run: |
          docker exec bitcoin bitcoin-cli -regtest -named createwallet wallet_name=testwallet
          echo "ADDRESS=$(docker exec bitcoin bitcoin-cli -regtest -rpcwallet=testwallet getnewaddress)" >> $GITHUB_ENV
      - name: Prepare Bitcoin
        run: |
          docker exec bitcoin bitcoin-cli -regtest -rpcwallet=testwallet generatetoaddress 101 $ADDRESS
          echo "TXID=$(docker exec bitcoin bitcoin-cli -regtest -rpcwallet=testwallet  listunspent | grep txid | cut -c14- | rev | cut -c3- | rev)" >> $GITHUB_ENV
      - name: Run integration tests
        run: sbt "integration / test"
      - uses: actions/download-artifact@v3
        with:
          path: cli/target/test-reports/
          name: unit-test-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success()
        with:
          files: |
            integration/target/test-reports/**/*.xml
            integration/target/it-reports/**/*.xml
