name: Check and Deploy
on:
  push:
    branches: ['*']
    tags: ["*"]

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Run unit tests
        run: sbt toplBtcBridge/test
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: topl-btc-bridge/target/test-reports/
  publish:
    name: Publish Docker Images for IT
    runs-on: ubuntu-20.04
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Log in to the Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to registries
        run: sbt "toplBtcBridge / Docker / publish"
        env:
          DOCKER_PUBLISH: true
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-20.04
    needs: publish
    services:
      # Label used to access the service container
      bifrost:
        # Docker Hub image
        image: docker.io/toplprotocol/bifrost-node:2.0.0-alpha10
        #
        ports:
           - 9084:9084
      bitcoin:
        # Docker Hub image
        image: docker.io/1maa/bitcoin:v25-regtest
        #
        ports:
          - 18444:18444  
        options: --name bitcoin
      topl-btc-bridge:
        # Docker Hub image
        image: ghcr.io/topl/topl-btc-bridge:latest
        #
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Prepare wallet
        run: |
          curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
          chmod +x cs
          ./cs setup --yes
          shopt -s expand_aliases
          alias brambl-cli="./cs launch -r https://s01.oss.sonatype.org/content/repositories/releases co.topl:brambl-cli_2.13:2.0.0-beta1 -- "
          export ADDRESS=$(brambl-cli wallet current-address --walletdb topl-btc-bridge/src/universal/topl-wallet.db)
          brambl-cli simple-transaction create --from-fellowship nofellowship --from-template genesis --from-interaction 1 --change-fellowship nofellowship --change-template genesis --change-interaction 1  -t $ADDRESS -w password -o genesisTx.pbuf -n private -a 1000 -h  127.0.0.1 --port 9084 --keyfile topl-btc-bridge/src/universal/topl-wallet.json --walletdb topl-btc-bridge/src/universal/topl-wallet.db --fee 10 --transfer-token lvl
          brambl-cli tx prove -i genesisTx.pbuf --walletdb topl-btc-bridge/src/universal/topl-wallet.db --keyfile topl-btc-bridge/src/universal/topl-wallet.json -w password -o genesisTxProved.pbuf
          brambl-cli tx broadcast -i genesisTxProved.pbuf -h 127.0.0.1 --port 9084
      - name: Run integration tests
        run: sbt "integration / test"
      - uses: actions/download-artifact@v3
        with:
          path: cli/target/test-reports/
          name: unit-test-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success()
        with:
          files: |
            integration/target/test-reports/**/*.xml
            integration/target/it-reports/**/*.xml
